site_name: MOMOBot
nav:
    - Overview: index.md
        - Hardware: hardware.md
        - Electronics: electronics.md
        - Software: software.md
    - Bonus:
        - Circuit Diagram Draw.io Links: bonus/cd_links.md
        - Flipsky VESC 4.12 Documentation: bonus/vesc_doc.md
theme: 
    name: readthedocs
    highlightjs: true
